spring:
  application:
    name: FEDET Epicerie Solidaire API
  datasource:
    url: 'jdbc:postgresql://localhost:5494/fedetEpicerieSolidaire'
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    vault:
      uri: http://localhost:8200
      token: hvs.CAESIP7P9MYdh9iUs5uNnQ_fRnx2NBezvzoPiQ93q0NxUp2xGh4KHGh2cy45bkJZbEYwTUNBZ0FuTVVPQW55ODdKbnE
      kv:
        enabled: true
        backend: secret
        application-name: jwt-passphrase
#  web:
#    cors:
#      allowed-origin-patterns: http://localhost:8100
#      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
#      allowed-headers: *
#      allow-credentials: true
#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG
#    root: DEBUG
---
spring.config.activate.on-profile: localhost
spring:
  datasource:
    url: "jdbc:h2:file:./target/db/embedded;MODE=POSTGRESQL;AUTO_SERVER=true"
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

---
spring.config.activate.on-profile: test
spring:
  datasource:
    url: "jdbc:h2:file:./target/db/embedded;MODE=POSTGRESQL;AUTO_SERVER=true"
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop


---
spring.config.activate.on-profile: production
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5494/fedetEpicerieSolidaire'
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
